environment:
  matrix:
    - TARGET_ARCH: x64
      CONDA_PY: 37
      CONDA_INSTALL_LOCN: C:\\Miniconda-x64
    - TARGET_ARCH: x64
      CONDA_PY: 38
      CONDA_INSTALL_LOCN: C:\\Miniconda3-x64

# We always use a 64-bit machine, but can build x86 distributions
# with the TARGET_ARCH variable.
platform:
    - x64

install:
    # Add path, activate `conda` and update conda.
    - cmd: call %CONDA_INSTALL_LOCN%\Scripts\activate.bat
    - cmd: conda.exe install --yes --quiet conda conda-build conda-verify
    - cmd: set PYTHONUNBUFFERED=1

# Skip .NET project specific build phase.
build: off

test_script:
    - conda build conda-recipe
