environment:

  matrix:
    - TARGET_ARCH: x64
      CONDA_PY: 27
      CONDA_INSTALL_LOCN: C:\\Miniconda-x64
    - TARGET_ARCH: x64
      CONDA_PY: 37
      CONDA_INSTALL_LOCN: C:\\Miniconda3-x64


# We always use a 64-bit machine, but can build x86 distributions
# with the TARGET_ARCH variable.
platform:
    - x64

install:
    # Add path, activate `conda` and update conda.
    - cmd: call %CONDA_INSTALL_LOCN%\Scripts\activate.bat
    - cmd: conda.exe update --yes --quiet conda

    - cmd: set PYTHONUNBUFFERED=1

    # Install the required packages
    - cmd: conda.exe install --yes flake8 pytest
    - cmd: pip.exe install zstandard
    - cmd: pip.exe install .

    # Create the test environments. Do this after install
    # so pip doesn't copy them to the build directory
    - cmd: bash.exe testing/setup_envs.sh

# Skip .NET project specific build phase.
build: off

test_script:
    - py.test.exe conda_pack --runslow -s -vv
