# Build only the master branch, tagged commits, and pull requests
branches:
  only:
    - master
    - /\d+\.\d+.*/
# Don't run the (redundant) branch build with a pull request
skip_branch_with_pr: true

environment:
  PYTHONUNBUFFERED: 1
  PYTHONIOENCODING: utf-8
  PYTHONLEGACYWINDOWSSTDIO: 1
  MINICONDA: C:\\Miniconda3-x64
  matrix:
    - PYTHON_VERSION: 3.7
    - PYTHON_VERSION: 2.7

matrix:
  fast_finish: true

# We always use a 64-bit machine, but can build x86 distributions
# with the TARGET_ARCH variable.
platform:
    - x64

install:
    - mkdir C:\Users\appveyor\.conda
    - call %MINICONDA%\Scripts\activate.bat
    - conda install -y conda conda-build conda-verify
    - conda info -a

# Skip .NET project specific build phase.
build: off

test_script:
    - conda build conda-recipe --python=%PYTHON_VERSION%
